package eu.hansolo.fx.charts;

public enum ChartType {
    SCATTER, LINE, SMOOTH_LINE, AREA, SMOOTH_AREA, BAR, BUBBLE, DONUT, RADAR_POLYGON, SMOOTH_RADAR_POLYGON, RADAR_SECTOR,
    HORIZON, SMOOTHED_HORIZON, MATRIX_HEATMAP
}
